name: CI - Validación Proyecto Web
on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Validar estructura de proyecto
        run: |
          test -f index.html
          test -f script.js
          test -f styles.css